class ChunkingConfig:
    MAX_SEGMENT_TOKENS = 4000
    MAX_PARENT_WINDOW_TOKENS = 2500
    TARGET_CHUNK_TOKENS = 300
    MIN_CHUNK_TOKENS = 200
    MAX_CHUNK_TOKENS = 400
    CHUNK_OVERLAP_SENTENCES = 2

config = ChunkingConfig()
